FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package.json ./
RUN corepack enable && yarn install

COPY frontend/ .
RUN yarn build

FROM nginx:alpine

COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
